name: Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      # Skipping deploys on changes in these files, remove if you need to
      - '.github/**'
      - '!.github/workflows/deployment*'
      - '**/*.md'
      - 'docs/**'
      - '*.md'
      - 'LICENSE'
  workflow_dispatch:

concurrency: deployment

jobs:
  deploy-sam:
    name: "Deploy SAM Application"
    uses: rewindio/github-action-sam-deploy/.github/workflows/deploy.yml@v3
    with:
      target_staging_regions: '["us-east-1"]'
      target_production_regions: '["us-east-1"]'
      stack_name: aws-cloudfront-auto-invalidator
      extra_sam_args: "--no-fail-on-empty-changeset --capabilities CAPABILITY_IAM"
      runner: ubuntu-latest-arm
    secrets:
      STAGING_AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN_SERVICE_TERRAFORM_STAGING }}
      PRODUCTION_AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN_SERVICE_TERRAFORM_PRODUCTION }}
      # Secrets are not accessible unless they are shared, so we need these three even though they are redundant.
      DEPLOY_FAILURES_SLACK_WEBHOOK_URL: ${{ secrets.DEPLOY_FAILURES_SLACK_WEBHOOK_URL }}
      DEPLOY_SUCCESS_SLACK_WEBHOOK_URL: ${{ secrets.DEPLOY_SUCCESS_SLACK_WEBHOOK_URL }}
      GITHUB_USER_LOOKUP_TOKEN: ${{ secrets.GH_USER_LOOKUP_TOKEN }}
      SLACK_DM_TOKEN: ${{ secrets.SLACK_DM_TOKEN }}
