name: Lint/Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Format
        uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e # stable

  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.13'

      - run: pip install -r requirements.txt

      - name: Unit Tests
        env:
          PYTHONPATH: .
        run: |
          set -o pipefail
          pytest --junitxml=pytest.xml --cov=src tests/test*.py | tee pytest-coverage.txt

      - name: Comment coverage
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: MishaKav/pytest-coverage-comment@dd5b80bde6d16941f336518e92929e89069d8451 # v1.7.2
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
